project:
  type: website
  output-dir: docs

website:
  title: "WACCBIP_RNA-seq_workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Command line analysis"
        href: lesson1_command_line.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

